version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - redis
    restart: unless-stopped
